FROM tomcat:8

ARG SPRING_PROFILES_ACTIVE
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-uat}
ENV TZ=Asia/Ho_Chi_Minh

RUN rm -rf /usr/local/tomcat/webapps/*
RUN sed -i 's/<Connector/<Connector allowTrace="false"/g' /usr/local/tomcat/conf/server.xml
COPY . /usr/local/tomcat/webapps/
CMD ["catalina.sh", "run"]
EXPOSE 8080
